services:
  marreta:
    container_name: marreta
    image: ghcr.io/manualdousuario/marreta:latest
    ports:
      - "80:80"
    volumes:
      - ./app/cache:/app/cache
    environment:
      # Configurações básicas
      - SITE_URL=
      ## Opcionais
      - SITE_NAME=
      - SITE_DESCRIPTION=
      - DNS_SERVERS=
      # Configurações de Cache S3
      - S3_CACHE_ENABLED=
      - S3_ACCESS_KEY=
      - S3_SECRET_KEY=
      - S3_BUCKET=
      - S3_REGION=
      - S3_FOLDER=
      - S3_ACL=
      - S3_ENDPOINT=
      # Configurações do LogOwl
      - LOGOWL_ENABLED=
      - LOGOWL_TICKET=
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
